### PR TITLE
Implemented #163: grep search feature

### PR DESCRIPTION
**Pull request by jacargentina**
Please review my code, and i hope can be merged on main repo too.
Any comments are welcome.
Cheers!

### CODE REVIEW

**Comment by jacargentina** [comment]
I've implemented this and already did a pull request (#164)

**Comment by jacargentina** [comment]
Ups, i closed the pull request by accident!

**Comment by reneflottweg63** [comment]
nice

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
