### PR TITLE
Atomic object writes

### PR DESCRIPTION
**Pull request by peff**
We occasionally see corrupted empty loose object files on GitHub after a machine failover. The problem is that Grit is not as careful with its object writes as Git itself. This PR should fix that.

/cc @rtomayko

### CODE REVIEW

**Comment by rtomayko** [comment]
This looks great.

**Comment by rtomayko** [comment]
Oops this is failing under Ruby 1.8.7 with:

```
ArgumentError: wrong number of arguments (3 for 2)
    /usr/share/rbenv/versions/ree-1.8.7-2012.02+github1/lib/ruby/1.8/tempfile.rb:184
    /usr/share/rbenv/versions/ree-1.8.7-2012.02+github1/lib/ruby/1.8/tempfile.rb:184
    /usr/share/rbenv/versions/ree-1.8.7-2012.02+github1/lib/ruby/1.8/tempfile.rb:184
    vendor/internal-gems/grit/lib/grit/git-ruby/internal/loose.rb:67
```

**Comment by rtomayko** [comment]
So 1.8.7 doesn't take the extra options argument. The mode default is:

> Creates a temporary file of mode 0600 in the temporary directory, **opens it with mode “w+”**, and returns a Tempfile object which represents the created temporary file. A Tempfile object can be treated just like a normal File object.

The w+ mode is:

> Read-write, truncates existing file to zero length or creates a new file for reading and writing.

Seems like maybe we could drop the argument entirely and roll with that. The other huge issue here though is encodings. If we drop the `wb` we'll likely run into encoding compatibility errors when writing binary data due to the attempted conversion to utf-8.

**Comment by rtomayko** [comment]
Fixed this up in b49a6ff4ccd169eef6671263ccb29d3ead957697. Should be fine.

**Comment by peff** [comment]
Yeah, exactly, I was worried about losing the "b" flag. Your fix looks good. Thanks.

**Pull request merged**
