### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by joliss**
- Add plenty of Ruby flavors to build with on Travis
  
  It doesn't build successfully with JRuby (yet), so we ignore build
  failures with JRuby for now.
- Add Travis and Gemnasium badges

Build is green: http://travis-ci.org/#!/joliss/grit
Don't forget to enable the build on http://travis-ci.org/profile

### CODE REVIEW

**Comment by joliss** [comment]
This requires #113 to be merged first.

**Comment by bootstraponline** [comment]
+1

**Comment by styx** [comment]
:+1:

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
