### PR TITLE
Fix an edge case in rev_parse.

### PR DESCRIPTION
**Pull request by sbryant**
## The Problem

Calling #rev_parse with a revision to parse that includes a ref and a path that contains `..` in the filename.
Example `HEAD:path/to/file/with/two..dots_in_the_file_name`

This will attempt to split and then rev_parse on the two parts. At best we'll get an error and git will tell us that the path doesn't exist. At worst we'll run into a situation where that fille will exist and we will be returning bad information.
## The Fix

Just don't split on revision specifiers that contain `:`.

### CODE REVIEW

**Comment by vmg** [comment]
This works, but is not pretty. On the other hand, rev-parse is not pretty, and I don't think there's any way to make it pretty.

:+1::shipit::+1:

**Comment by rtomayko** [comment]
God, why? Can't you just call rev-parse twice?

**Comment by vmg** [comment]
@rtomayko: I don't follow. How would that fix the issue? The paths becomes broken after the first rev-parse.

**Comment by rtomayko** [comment]
Sorry, I misread the diff and thought you were _adding_ splitting which makes no sense to me in the first place. Sigh. Merging.

**Pull request merged**
