### PR TITLE
Memoize index

### PR DESCRIPTION
**Pull request by georgeguimaraes**
Hello,

I had some problems when using something like:
@repo.index.read_tree('master)
@repo.index.add(...)

Because each time the .index method is called, a new Grit::Index is returned with an empty tree.

This commit memoizes this Index to @index

### CODE REVIEW

**Comment by technoweenie** [comment]
An index is only valid for the duration of the commit.  This won't work if you try to use the same repo instance to make multiple commits.  Some suggestions:

```
@repo.index.read_tree('master')
@repo.index.add('...')
@repo.commit...

@repo.index(reload=true).read_tree('master')
```

Or, don't memoize it and check for a block:

```
index = @repo.index
# or
@repo.index do |idx|
  idx.read_tree('master')
  idx.....
end
```

I personally like the block idea because it doesn't change the behavior of `Repo#index`.

**Comment by rtomayko** [comment]
Yeah. If we memoize, it should be reset to nil on the call to `Grit::Repo#commit`. I think we could do both the memoized and block forms if we reset after commit, though.

**Comment by kelvinst** [comment]
Ressurecting this! So, part of me agree with you @rtomayko, but an other part stays afraid from the consequences of it.

Does grit eliminates the possibility of outside changes in the repositories? Or it have some kind of monitoring through them? If not, I think that this change is too dangerous, since I can call a `git commit` at the repo from outside the grit API.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
