### PR TITLE
Bugfixes for Ruby 2.0

### PR DESCRIPTION
**Pull request by BertramScharpf**
I tried to run it with Ruby 2.0 but it crashed. I had to fix two bugs what is contained in the first commit.

The second commit just contains some newlines in files that did not end in newlines.

The third commit just makes the compatibility solution smarter.

### CODE REVIEW

**Comment by zacksiri** [comment]
+1 for this

**Comment by BertramScharpf** [comment]
They are severe bugs. I did not complain but just wrote a fix. The fixes are really obvious. So, why don't you just merge it?

**Comment by paulRbr** [comment]
:+1: clearly this needs to be in

**Comment by maximerety** [comment]
+1

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
