### PR TITLE
Handle encoding header of Git commits when possible.

### PR DESCRIPTION
**Pull request by akzhan**
Handle encoding header of Git commits when possible.

### CODE REVIEW

**Comment by akzhan** [comment]
It should correctly work on Ruby 1.9 series.

May be iconv will be required on ruby 1.8 but currently this code simply does nothing on ruby 1.8.

**Comment by akzhan** [comment]
- encoding and decoded_message properties added on pure ruby commits.
- initial git to ruby encoding mapping added (should be extended by reviewing of map warnings).
- message property of Grit::Commit now is utf-8 always.

**Comment by akzhan** [comment]
Ruby 1.8 code and tests will arrive in week.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Comment by akzhan** [comment]
Thanks for feedback.

**Pull request closed without merging**
