### PR TITLE
Added UTF-8 to filenames

### PR DESCRIPTION
**Pull request by piotreq**
After this change grit manages with filenames containing ąśćłóż characters in filenames (Useful with gollum)

### CODE REVIEW

**Comment by bootstraponline** [comment]
+1

**Comment by rioki** [comment]
+1

**Comment by 3100** [comment]
+1

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
