### PR TITLE
Use appropriate working tree in git commands

### PR DESCRIPTION
**Pull request by lambda**
I was working on a script that needed to manipulate the working tree of a Git repo. While Grit appeared to handle non-bare repos, it passed in the `--git-dir` parameter but never passed the `--work-tree` parameter to Git, causing it to do all working tree manipulations in the current working directory instead of the working tree of the repo it was supposed to work in. I've provided a patch that fixes that, which passes the working tree into the external Git command if working with a non-bare repo. 

This patch doesn't affect bare repos, and doesn't affect any usage which doesn't touch the working tree. All unit tests still pass with this patch. The patch does not include any new unit tests to test the new functionality, however, as it looked like more worth than I wanted to do to set up the testing infrastructure for that use case. Let me know if you need tests for this.

There are also a couple of cleanup patches here; one which fixed a unit test that failed when I ran it in my timezone (and also failed if I ran it against half-hour timezones), and one which removes some vestigial code.

### CODE REVIEW

**Comment by rtomayko** [comment]
Looks good to me. I've been bit by this as well. The one problem I see is that it could break people that rely on the current behavior of using the working directory as the work tree. Let's get mojombo to weigh in on how we should handle backward incompatible changes like that. Feels like a pretty big edge case to me but it's backward incompatible none the less.

**Comment by scollett** [comment]
Any plans to add this patch? I've been bitten too.

**Comment by nand2** [comment]
While this is not merged yet, this little dirty trick can help:

```
mypath = '/xx/xx'
repo = Grit::Repo.new(mypath)
[..]
repo.git.reset({:env => {'GIT_WORK_TREE' => mypath}, :hard => true}, commit_id)
```

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
