### PR TITLE
Fix git executable search on windows.

### PR DESCRIPTION
**Pull request by Ziaw**
Grit can't find git.exe on windows.

### CODE REVIEW

**Comment by khustochka** [comment]
This patch calculates path properly but then spawn fails with 'Bad file descriptor'.

Oh, OK, it works on edge.

**Comment by rioki** [comment]
I actually analysed the issue while trying to get gollum to work on win32. See github/gollum#23 for the total hack I did. The Bad file descriptor can be "solved" by changing the call `fd.write_nonblock` in Process::read_and_write (Process.rb:162) to `fd.write`. I don't know what the real issue here is, tho...

**Comment by wernight** [comment]
For git-up it also requires https://github.com/stereobooster/posix-spawn/commit/67a73c670f3836f137dd06ea854ea71cc1d12154

**Comment by wernight** [comment]
After applying the posix-spawn patch, I found the directory separator must also be changed (see `map  { |p| p.gsub!('\', '/') } below):

```
class << self
  attr_accessor :git_timeout, :git_max_size
  def git_binary
    @git_binary ||=
      ENV['PATH'].split(File::PATH_SEPARATOR).
        map  { |p| File.join(p, 'git') }.
        find { |p| File.exist?(p) }
    # Windows PATH search
    @git_binary ||=
      ENV['PATH'].split(File::PATH_SEPARATOR).
        map  { |p| File.join(p, 'git.exe') }.
        map  { |p| p.gsub!('\\', '/') }.
        find { |p| File.exist?(p) }
  end
  attr_writer :git_binary
end
```

Then it mostly works on msysgit. Only thing remains are the colors. Possibly using _smart_colored_ in place of _colored_. Colored uses the deprecated win32console which has been replaced by https://github.com/adoxa/ansicon (and may work).

A simple fix in the mean time is via https://github.com/adoxa/ansicon:

```
$ ansicon git up
```

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
