### PR TITLE
Index#write_tree won't remove directories

### PR DESCRIPTION
**Pull request by koraktor**
Working on [Silo](http://koraktor.de/silo) I stumbled upon `Grit::Index#write_tree` not removing directories when paths are not suffixed with a slash. Additionally `Grit::Index#add` will always strip a trailing slash due to `split('/')`. So you won't be able to delete a directory at all using `Grit::Index#delete`.

I think this is generally undesired as you're otherwise not required to suffix directory or tree paths with a slash.

I added two patches adding a test for that issue and also fixing the problem in `Index#write_tree`.

### CODE REVIEW

**Comment by rtomayko** [comment]
Hmm. I'm not very familiar with this area of the project. Your changes seem sane to me.

One quick comment:

> I think this is generally undesired as you're otherwise not required to suffix directory or tree paths with a slash.

I do know `git-ls-tree` works differently when you give it a path/with/slash/ vs a path/with/no/slash, so its not entirely without precedent. I don't see how that would apply here, though.

**Comment by koraktor** [comment]
The problem here originates from the way how Grit uses `Hash`es to represent trees. I don't think it would be good to change that, so my change seems like a good solution for the problem of not being able to remove directories.

**Comment by koraktor** [comment]
@mojombo, @rtomayko, @schacon: Any suggestions / objections on this one?

**Comment by ef4** [comment]
I hit this bug and was about to make this very same change.  I think it should get merged.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
