### PR TITLE
Parse log by looking at the text rather than assuming a specific order

### PR DESCRIPTION
**Pull request by DougPuchalski**
Previous method did not work when using the -g option, for example.

### CODE REVIEW

**Comment by brynary** [comment]
I've started seeing some failures in this method from commits with a gpgsig section. Have you run into this?

**Comment by DougPuchalski** [comment]
No, sorry. Seems like no interest in pulling this but this functionality is clearly broken.

**Comment by brynary** [comment]
Thanks. This change seems to fail a lot of tests for me. Is it running green for you?

**Comment by DougPuchalski** [comment]
Thanks, missed that. I have rebased and issued a new pull request.

https://github.com/mojombo/grit/pull/124

**Pull request closed without merging**
