### PR TITLE
Clearly state the project status

### PR DESCRIPTION
**Pull request by bkeepers**
GitHub is transitioning off of Grit. This updates the README to state that grit is unmaintained and points to [libgit2/rugged](https://github.com/libgit2/rugged).

I suggest we close all open pull requests with a link to this pull request, and update the project description to indicate the current state.

/cc @mojombo @rtomayko @peff

### CODE REVIEW

**Comment by peff** [comment]
No complaint here. The Rugged code should be better tested and maintained at this point. There might be places where it is missing features that Grit has, but I suspect they are not many these days. /cc @vmg and @arrbee

**Comment by vmg** [comment]
Burn it to the ground. I don't think there are any features not implemented in Rugged atm, so I definitely support closing all open issues and PRs in the repository.

**Comment by arrbee** [comment]
:+1: I'll be happy go through the Rugged vs Grit APIs a little more carefully and make sure that Rugged isn't missing anything important.

**Comment by rtomayko** [comment]
:+1:

**Comment by bkeepers** [comment]
I don't have commit access, so someone either want to add me to the repo or lead the charge on this?

**Pull request merged**
