### PR TITLE
Make refs support submodules

### PR DESCRIPTION
**Pull request by ekohl**
In a submodule the git_dir is actually a file which contains the location of the actual git dir in the format gitdir: my/actual/dir.

I've already verified manually that it solves my issue (https://github.com/aanand/git-up/issues/31) but I'm quite new to ruby and grit so I could use some advice on how to write the unit tests.

### CODE REVIEW

**Comment by ekohl** [comment]
According to https://github.com/ktoso/maven-git-commit-id-plugin/issues/19#issuecomment-3077417 this changed in 1.7.8. From https://lkml.org/lkml/2011/12/2/316:
- When populating a new submodule directory with "git submodule init",
  the $GIT_DIR metainformation directory for submodules is created inside
  $GIT_DIR/modules/<name>/ directory of the superproject and referenced
  via the gitfile mechanism. This is to make it possible to switch
  between commits in the superproject that has and does not have the
  submodule in the tree without re-cloning.

**Comment by jakearchibald** [comment]
Would love to see this rolled in

**Comment by jfirebaugh** [comment]
:+1: I ran into this problem trying to use [git up](https://github.com/aanand/git-up) within a submodule. See aanand/git-up#24 and aanand/git-up#31.

**Comment by vad4msiu** [comment]
+1

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
