### PR TITLE
Faster tree parsing

### PR DESCRIPTION
**Pull request by ef4**
This patch results in a significant speedup for workloads that involve parsing a lot of trees. It also reduces 29 lines of code down to 3.

There are two optimizations:
1. Eliminate a slow manual conversion from base10 string to base8 integer. This actually showed up as a hot spot while profiling.
2. Use a regex to parse the tree object itself, instead of doing byte-by-byte comparisons.

### CODE REVIEW

**Comment by dzaporozhets** [comment]
how it will improve performance?
~ %

**Comment by ef4** [comment]
I'm seeing seeing a speedup of 30 to 40% for traversing a tree of about 24000 nodes.

**Comment by dzaporozhets** [comment]
thanks

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Pull request closed without merging**
